/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

/**
 *
 * @author miguela
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ambiente = new javax.swing.JDesktopPane();
        MENUPRINCIPAL = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        med1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        func1 = new javax.swing.JMenu();
        func2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuutil = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FARMÁCIA");

        javax.swing.GroupLayout ambienteLayout = new javax.swing.GroupLayout(ambiente);
        ambiente.setLayout(ambienteLayout);
        ambienteLayout.setHorizontalGroup(
            ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        ambienteLayout.setVerticalGroup(
            ambienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jMenu1.setText("HOME");

        jMenuItem15.setText("AJUDA");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setText("SOBRE");
        jMenu1.add(jMenuItem16);

        jMenuItem17.setText("SAIR");
        jMenu1.add(jMenuItem17);

        MENUPRINCIPAL.add(jMenu1);

        jMenu3.setText("MEDICAMENTOS");

        med1.setText("ADICIONAR");
        med1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med1ActionPerformed(evt);
            }
        });
        jMenu3.add(med1);

        jMenuItem12.setText("ALTERAR");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("REMOVER");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("PESQUISAR");
        jMenu3.add(jMenuItem14);

        MENUPRINCIPAL.add(jMenu3);

        func1.setText("FUNCIONÁRIOS");

        func2.setText("ADICIONAR");
        func2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func2ActionPerformed(evt);
            }
        });
        func1.add(func2);

        jMenuItem8.setText("ALTERAR");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        func1.add(jMenuItem8);

        jMenuItem9.setText("REMOVER");
        func1.add(jMenuItem9);

        jMenuItem10.setText("PESQUISAR");
        func1.add(jMenuItem10);

        MENUPRINCIPAL.add(func1);

        menuutil.setText("UTILITÁRIOS");
        menuutil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuutilMouseClicked(evt);
            }
        });
        menuutil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuutilActionPerformed(evt);
            }
        });
        MENUPRINCIPAL.add(menuutil);

        jMenu5.setText("VENDAS");

        jMenuItem1.setText("ALTERAR");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("APAGAR");
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("PESQUISAR");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("RELATÓRIOS");
        jMenu5.add(jMenuItem4);

        MENUPRINCIPAL.add(jMenu5);

        setJMenuBar(MENUPRINCIPAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ambiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ambiente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void med1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med1ActionPerformed
        // TODO add your handling code here:
        cadastromedicamento telcadmed=new cadastromedicamento();
        ambiente.add(telcadmed);
        telcadmed.setVisible(true);
    }//GEN-LAST:event_med1ActionPerformed

    private void func2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func2ActionPerformed
        // TODO add your handling code here:
        cadastrofuncionario telcad=new cadastrofuncionario();
        ambiente.add(telcad);
        telcad.setVisible(true);
    }//GEN-LAST:event_func2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuutilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuutilActionPerformed
        // TODO add your handling code here:
        utilitario telutil=new utilitario();
        ambiente.add(telutil);
        telutil.setVisible(true);
    }//GEN-LAST:event_menuutilActionPerformed

    private void menuutilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuutilMouseClicked
        // TODO add your handling code here:
        utilitario telutil=new utilitario();
        ambiente.add(telutil);
        telutil.setVisible(true);
    }//GEN-LAST:event_menuutilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MENUPRINCIPAL;
    private javax.swing.JDesktopPane ambiente;
    private javax.swing.JMenu func1;
    private javax.swing.JMenuItem func2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem med1;
    private javax.swing.JMenu menuutil;
    // End of variables declaration//GEN-END:variables
}
